name: update

on: 
  workflow_dispatch:
  push:
   branches: master
  schedule:
    - cron: '5 13 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: copy 
      run: |
        git config --global user.email actionbot@email.com
        git config --global user.name actionbot
        git clone https://github.com/Baiyuetribe/kamiFaka.git
        cp -rf kamiFaka/dist/*  latest
        cp -rf kamiFaka/dist/admin.html  admin.html
        cp -rf kamiFaka/dist/index.html  index.html
        rm -rf kamiFaka
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "/static"
        replace: "https://cdn.jsdelivr.net/gh/Ecalose/cdn@main/latest/static"
        include: "latest/.html"
    - name: commit
      run: |
        chmod +x ./update-repo.sh&&./update-repo.sh 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.CDN }}
        force: true
