name: update

on: 
  workflow_dispatch:
  push:
   branches: main
  schedule:
    - cron: '5 13 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Commit #上传新的refresh_token到仓库
      run: |
        cd latest
        git init
        git remote add origin https://github.com/Baiyuetribe/kamiFaka.git
        git config core.sparsecheckout true
        echo "dist" >> .git/info/sparse-checkout
        git pull origin master
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
